# -*- coding: utf-8 -*-
"""과제1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yEEwHnYKzqLTAroYOOLaqRj24bRpeNRK
"""

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
import pandas as pd

breast_cancer_data = load_breast_cancer()

df_data = pd.DataFrame(breast_cancer_data.data)

df_labels = pd.DataFrame(breast_cancer_data.target)

print(df_data[:10])
print(df_labels[:10])

print(breast_cancer_data.target_names)

X=breast_cancer_data.data
y=breast_cancer_data.target
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)
print("X_train.shape :", X_train.shape)

print("y_train.shape :", y_train.shape)

print("X_test.shape:", X_test.shape)

print("y_test.shape:", y_test.shape)

from sklearn.neighbors import KNeighborsClassifier


mymodel=KNeighborsClassifier(n_neighbors=3)

mymodel.fit(X_train,y_train)

# 예측

#prediction = mymodel.predict(X_test)

mymodel.score(X_test, y_test)